import React, { createContext, useEffect, useState } from "react";
import { Route, BrowserRouter as Router, Routes } from "react-router-dom";
import AfterSubmit from "./AfterSubmit"; // Import AfterSubmit component
import Home from "./Home"; // Import Home component
import RulesView from "./karan_treeview/RulesView"; // Adjust the import according to your file structure
import { apiEditorData } from "./karan_treeview/mockData";
import { removeField } from "./karan_treeview/utils";

export const AppContext = createContext();
function App() {
  const [dataQualityStates, setDataQualityStates] = useState(null);

  useEffect(() => {
    const baseLineRules = JSON.parse(JSON.stringify(apiEditorData));
    removeField(baseLineRules, "optional");
    setDataQualityStates({
      ...dataQualityStates,
      addMoreColumnRules: apiEditorData,
      autoGeneratedRules: apiEditorData,
    });
  }, []); // eslint-disable-line

  return (
    <Router>
      {dataQualityStates && (
        <AppContext.Provider value={{ dataQualityStates, setDataQualityStates }}>
          <Routes>
            <Route path="/rules" element={<RulesView />} />
            <Route path="/after-submit" element={<AfterSubmit />} /> {/* Add AfterSubmit route */}
            <Route path="/" element={<Home />} /> {/* Add Home route */}
            {/* <Route path="/another" element={<AnotherComponent />} /> */}
          </Routes>
        </AppContext.Provider>
      )}
    </Router>
  );
}

export default App;