import { Editor } from "@monaco-editor/react";
import React, { useContext } from "react";
import { AppContext } from "../../App";
import { removeField, removeHiddenObjs, removeUncheckedObjs } from "../utils";

const EditorView = ({ editorBaseLine }) => {
  const { dataQualityStates } = useContext(AppContext);
  const autoGeneratedRules = dataQualityStates.autoGeneratedRules;
  removeField(editorBaseLine, "optional");
  removeField(editorBaseLine, "hidden_columns");
  removeUncheckedObjs(editorBaseLine);
  removeHiddenObjs(editorBaseLine);

  const handleEditorChange = (value) => {
    try {
      const parsedValue = JSON.parse(value);
      Object.keys(autoGeneratedRules).forEach((key) => {
        if (parsedValue[key]) {
          if (parsedValue[key].length >= 0) {
            autoGeneratedRules[key] = parsedValue[key];
            return;
          }
          Object.keys(autoGeneratedRules[key]).forEach((k) => {
            if (parsedValue[key][k]) {
              if (parsedValue[key][k].length >= 0) {
                autoGeneratedRules[key][k] = parsedValue[key][k];
                return;
              }
              autoGeneratedRules[key][k] = { ...autoGeneratedRules[key][k], ...parsedValue[key][k] };
            }
          });
        }
      });
    } catch (e) {
      console.error("Invalid JSON input", e);
    }
  };

  const editorBaseLineString = JSON.stringify(editorBaseLine, null, 4);
  return (
    <Editor
      height="90vh"
      defaultValue={editorBaseLineString || "// some comment"}
      defaultLanguage="json"
      value={editorBaseLineString}
      onChange={handleEditorChange}
    />
  );
};

export default EditorView;
